### ISSUE TITLE
Get All Users or User to show limited user data

### ISSUE THREAD

**Issue by mayeedwin** [mainawycliffe/kamanda#9]
1. Could show email, name and or last time logged in or service provider

**Comment by mainawycliffe** [comment]
Thanks @mayeedwin, let me see what information I can get back from Firebase and see which fields to prioritize. I am also thinking of making the UI interactable, so that when you click or select a user in the table, it shows you more information.

**Comment by mayeedwin** [comment]
Sure or prompts to show minimal or all data for example

```bash
PS C:\Users\admin\Documents\GitHub\todocodee> Show minimal ( Yes / No)
```

**Comment by mainawycliffe** [comment]
I am releasing a new version with a `--minimalUI` flag, should go to version `0.3.0`

**Comment by mayeedwin** [comment]
Good work @mainawycliffe

**Comment by mainawycliffe** [comment]
Fixed a bug that came from this issue.

**Comment by mainawycliffe** [comment]
I am just wondering whether to invert the options, i.e. minimal ui by default and the interactive view to be behind a flag like `kamanda auth list --interactive`

**Comment by mayeedwin** [comment]
Looks good...alternatives is sauce
